version: '3.5'

services:
  ieuw-db:
    container_name: postgresql-ieuw
    image: postgres
    environment:
      POSTGRES_DB: my-db
      POSTGRES_USER: my-user
      POSTGRES_PASSWORD: my-password
    ports:
      - 2345:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
